### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by cuthulino** [MuellerConstantin/qdata#1]
Hello,
I am missing a "How to run this".

Could you explain what to do to run this code?

1. git clone repository
2. ...

The Screenshot looks very nice!
Thanks.

**Comment by MuellerConstantin** [comment]
Hey, this software is still in an early stage of development. Therefore, there are no executable binaries for the end user yet. Of course, the project can be downloaded and started. However, this requires a Python runtime environment and the installation of all required dependencies (`$ pip install -r requirements.txt`); this step is only recommended for developers, not for end users.

If you still want to start the project via the Python runtime environment, take a look at the [tasks.py](https://github.com/MuellerConstantin/qdata/blob/main/tasks.py) file. This file contains the steps of the software's build process and also a task (`$ invoke run`) for running the root module as a python script without compiling it.

**Comment by cuthulino** [comment]
Thanks, now I got it.
I struggled with the missing resources error.
The tasks.py helped here.

For everyone else:

1. `git clone` the repository
2. `cd` into cloned path
3. create venv `python.exe -m venv .`
4. activate venv
5. install requirements `python.exe -m pip install -r .\requirements.txt`
6. resources qrc to py `pyside6-rcc -o .\qdata\resources.py .\resources\resources.qrc`
7. run it `python.exe -m qdata`

**Comment by MuellerConstantin** [comment]
There is a first development build for `windows` and `linux` in the [release section](https://github.com/MuellerConstantin/qdata/releases) now. However, this build is still not intended for end user usage and does only represent the current state of development.
